name: ASP.NET Core CI

on:
  push:
    branches: [ "master" ]   # Run on push to main
  pull_request:
    branches: [ "master" ]   # Run on PRs targeting main

jobs:
  build:
    runs-on: windows-latest   # You can also use windows-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # project's version (8.0)

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore
